// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfFlowKey struct {
	_      structs.HostLayout
	Saddr  [16]uint8
	Daddr  [16]uint8
	Sport  uint16
	Dport  uint16
	Family uint16
}

type bpfStartVal struct {
	_        structs.HostLayout
	Ts       uint64
	LastEmit uint64
	Rx       uint64
	Tx       uint64
	Pid      uint32
	Family   uint16
	Sport    uint16
	Dport    uint16
	Dir      uint8
	State    uint8
	Proto    uint8
	Saddr    [16]uint8
	Daddr    [16]uint8
	Comm     [16]int8
	_        [3]byte
}

type bpfUdpVal struct {
	_       structs.HostLayout
	Sv      bpfStartVal
	Prev    bpfFlowKey
	HasPrev uint8
	Pad     [7]uint8
	_       [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents              = "events"
	bpfMapStart               = "start"
	bpfMapUdpHeads            = "udp_heads"
	bpfMapUdpStart            = "udp_start"
	bpfProgInetCskAcceptExit  = "inet_csk_accept_exit"
	bpfProgTcpCleanup         = "tcp_cleanup"
	bpfProgTcpSendmsgExit     = "tcp_sendmsg_exit"
	bpfProgTcpState           = "tcp_state"
	bpfProgUdpDestroySockExit = "udp_destroy_sock_exit"
	bpfProgUdpRecvmsgExit     = "udp_recvmsg_exit"
	bpfProgUdpSendmsgExit     = "udp_sendmsg_exit"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	InetCskAcceptExit  *ebpf.ProgramSpec `ebpf:"inet_csk_accept_exit"`
	TcpCleanup         *ebpf.ProgramSpec `ebpf:"tcp_cleanup"`
	TcpSendmsgExit     *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_exit"`
	TcpState           *ebpf.ProgramSpec `ebpf:"tcp_state"`
	UdpDestroySockExit *ebpf.ProgramSpec `ebpf:"udp_destroy_sock_exit"`
	UdpRecvmsgExit     *ebpf.ProgramSpec `ebpf:"udp_recvmsg_exit"`
	UdpSendmsgExit     *ebpf.ProgramSpec `ebpf:"udp_sendmsg_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	Start    *ebpf.MapSpec `ebpf:"start"`
	UdpHeads *ebpf.MapSpec `ebpf:"udp_heads"`
	UdpStart *ebpf.MapSpec `ebpf:"udp_start"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	Start    *ebpf.Map `ebpf:"start"`
	UdpHeads *ebpf.Map `ebpf:"udp_heads"`
	UdpStart *ebpf.Map `ebpf:"udp_start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.Start,
		m.UdpHeads,
		m.UdpStart,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	InetCskAcceptExit  *ebpf.Program `ebpf:"inet_csk_accept_exit"`
	TcpCleanup         *ebpf.Program `ebpf:"tcp_cleanup"`
	TcpSendmsgExit     *ebpf.Program `ebpf:"tcp_sendmsg_exit"`
	TcpState           *ebpf.Program `ebpf:"tcp_state"`
	UdpDestroySockExit *ebpf.Program `ebpf:"udp_destroy_sock_exit"`
	UdpRecvmsgExit     *ebpf.Program `ebpf:"udp_recvmsg_exit"`
	UdpSendmsgExit     *ebpf.Program `ebpf:"udp_sendmsg_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.InetCskAcceptExit,
		p.TcpCleanup,
		p.TcpSendmsgExit,
		p.TcpState,
		p.UdpDestroySockExit,
		p.UdpRecvmsgExit,
		p.UdpSendmsgExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
